# 数据库相关配置
sql_db:
  host: api.lemonban.com
  user: future
  password: "123456"
  database: future

## pp_app 配置信息 todo
#  PP_DEVICE_ID:"A84076CC-2FC7-47C8-A1B6-0E2F5D693E52"
#  PP_DEVICE_TYPE:"IOS"
#  PP_CLIENT_VER:"5.3.0&2402281"
pp_app:
  device_id: "bee648d4b0a5ab70012345"
  device_type: "ANDROID"
  device_ver: "5.3.0&603020703"
